### ISSUE TITLE
Issue with Janus Events in Loki

### ISSUE THREAD

**Issue by geo-matheou** [sipcapture/paStash#117]
Hello, 

I am using the qxip/pastash-loki docker image and the configuration described in https://github.com/sipcapture/paStash/wiki/Example:-Janus-Events to store Janus Events into Loki. 

However, it seems that the Loki labels created when I store the data are not the same with the ones shown in examples. 

Attached you can find a screenshot of the labels created in my system. Useful labels such as emitter, handle_id, opaque_id, etc., are not created. How can I solve this issue? 

Thank you in advance,
George

![image](https://user-images.githubusercontent.com/34241098/164993400-004de529-3d58-499c-8430-dde9334d6417.png)

**Comment by lmangani** [comment]
@geo-matheou the beauty of loki (or even better, our cLoki) is you don't need to extract labels from the object or index them. Just set enough labels to find your Janus events by type, and then use the `| json` parser to extract your session labels. This will keep label cadinality low (any dymanic value would harm that) and will use the pipeline as per design, parsing at query time. Here's a useful example, to select by type and then extract any of the object value as metric or tag/groupby:
```
avg_over_time({type="32"} | json remote="event[\"lost-by-remote\"]" | unwrap remote [5s]) by (emitter)
```

**Comment by geo-matheou** [comment]
@lmangani thank you very much for your prompt reply. cLoki is very interesting project and I hope that I will use it in the future. For now, the requirement is to stream logs to an existing Loki system.

It seems that I had issues with labels because the grouping field in janus.eventhandler.sampleevh.cfg was set to true. When I set it to false everything is working fine.
