### ISSUE TITLE
Splitting Modules from Core

### ISSUE THREAD

**Issue by lmangani** [sipcapture/paStash#17]
@all paStash is growing a number of modules, and risks looking a pinch too monolithic for the possibilities NodeJS offers. Is anyone willing to help out moving a few modules (and their dependencies) outside of the core? Any help, suggestion or contribution is well appreciated!

**Comment by xycloud** [comment]
yes, take a look at koa. just keep a plugin framework ( and optionally keeping some core plugins.)

**Comment by lmangani** [comment]
Long overdue update here for those interested: https://github.com/lmangani/pastash_plugins
