### ISSUE TITLE
filtering netflow fields

### ISSUE THREAD

**Issue by Alisher-Nabiev** [sipcapture/paStash#192]
Hi, I am using NetFlow to receive data from a port. I am trying to filter the data and output certain fields to Elasticsearch.

This is the information that I am trying to read off :
"last_switched",
      "first_switched",
      "in_pkts",
      "input_snmp",
      "output_snmp",
      "src_tos",
      "ipv4_next_hop",
      "dst_mask",
      "src_mask",
      "tcp_flags",
      "in_dst_mac",
      "out_src_mac",
      "postNATSourceIPv4Address",
      "postNATDestinationIPv4Address",
      "postNAPTSourceTransportPort",
      "postNAPTDestinationTransportPort",
      "fsId",

but didn't find any way to filter the incoming data. 
can someone pls guide me on how can i achieve this?

**Comment by lmangani** [comment]
Hello @Alisher-Nabiev 
You should be able to use the [omit](https://github.com/sipcapture/paStash/blob/next/docs/filters/omit.md) filter for this task

**Comment by Alisher-Nabiev** [comment]
thanks helped a lot!
