### ISSUE TITLE
Pastash running only on one CPU and it's not enough

### ISSUE THREAD

**Issue by yaniv999** [sipcapture/paStash#223]
we are using Pastash with sqlite filter
we are running a quarry :

filter {
  sqlite {
    db => '/home/usersip.db'
    query => 'SELECT CustomerName FROM UserData WHERE IP=(?) LIMIT 1;'
    source_field => 'ipv4_src_addr'
    target_field => 'CustomerNane'
    }
}

The problem is that the UserData table is quite big and the CPU doesn't manage to handle it
ElasticSearch is getting 1% of the data

and the CPU is on 100%
![image](https://github.com/user-attachments/assets/1b3339aa-2a5e-4814-b579-8dd47fe986e4)

Is it possible for Pastash to use more than one CPU?

**Comment by lmangani** [comment]
NodeJS is single threaded. You can use [pm2 with cluster mode](https://pm2.keymetrics.io/docs/usage/cluster-mode/) to distribute load between multiple pastash instances.

On the other end, this shows the current sqlite approach is probably not the ideal without a good caching mechanism.
