### ISSUE TITLE
add hours to index name

### ISSUE THREAD

**Issue by Alisher-Nabiev** [sipcapture/paStash#228]
i am trying to configuring my index like this

output {
  elasticsearch {
    host => 0.0.0.0
    port => 9200
    bulk_limit => 1000
    bulk_timeout => 100
    pipeline => imei-pipeline
    **index_prefix => "netflow-%{+YYYY-MM-dd.HH}"**
    data_type => netflow
  }
}

but it now working i tried to run the DEBUG and its shows like evriting is ok but still don't receive any doc to my index.

it work for me only like this:
output {
  elasticsearch {
    host => 0.0.0.0
    port => 9200
    bulk_limit => 1000
    bulk_timeout => 100
    pipeline => imei-pipeline
    **index_prefix => netflow**
    data_type => netflow
  }
}

also tried this conf:
output {
  elasticsearch {
    host => 0.0.0.0
    port => 9200
    bulk_limit => 1000
    bulk_timeout => 100
    pipeline => imei-pipeline
    **index => netflow-%{+YYYY-MM-dd.HH}**
    data_type => netflow
  }
}

also don't work

**Comment by lmangani** [comment]
The format you're using doesn't seem to be valid. Try something like `#{now:YYYY-MM-dd.HH}`

**Comment by Alisher-Nabiev** [comment]
like this?  index_prefix => netflow-{now:YYYY-MM-dd.HH} 
it doesn't work 
also this 
 index_prefix => netflow-{YYYY-MM-dd.HH}
also this 
 index_prefix => "netflow-%{now:YYYY-MM-dd.HH}"

this configuration index => netflow-%{+YYYY-MM-dd.HH}   working for me on logstash in another service

**Comment by lmangani** [comment]
This is not logstash. The syntax is different and needs to be followed. In your example above it seems you did not.
```
index => 'netflow-#{now:YYYY-MM-dd.HH}'
```

**Comment by Alisher-Nabiev** [comment]
still not working do i need add in the filter this?

filter {
  date {
    match => ["EventTime", "UNIX_MS" ]
    target => "@timestamp"
  }

**Comment by lmangani** [comment]
It works fine for me. The date format is from the 'moment' library

```
 compute_field {
    field => index
    value => 'test-#{now:YYYY}'
  }
```

```
{
  "source": "stdin",
  "message": "test",
  "@timestamp": "2024-08-05T14:24:06.064Z",
  "type": "stdin",
  "index": "test-2024"
}
```
