### ISSUE TITLE
Multiple Hosts

### ISSUE THREAD

**Issue by Alisher-Nabiev** [sipcapture/paStash#235]
how can i use Multiple Hosts in output to elasticsearch:

output {

  elasticsearch {
    host => 0.0.0.0    <-- need to add another host
    port => 9200
    bulk_limit => 1000
    bulk_timeout => 100
    pipeline => imei-pipeline
    index_prefix => netflow
    data_type => netflow
  }
}

**Comment by braindawg** [comment]
I'm not sure there's a way to do this. I want to set up outputs to multiple MySQL databases (to get live data in both my production and staging environments), but have not been able to start 2 outputs using the same plugin without error.

**Comment by Dletta** [comment]
You can setup a second output inside the output.

```
output {
 elasticsearch {}
 elasticsearch {}
 }
 ```
