### ISSUE TITLE
Hep split via 

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/paStash#29]
Hi,
I tried to use this example do duplicate some udp hep to both servers :

https://github.com/sipcapture/paStash/wiki/Example:-HEP-Relay

But cannot obtain what i expected. :

Config :

`input {
  udp {
    host => 172.16.0.112
    port => 9060
  }
}

output {
  udp {
    host => 172.16.0.95
    port => 9060
  }
  udp {
    host => 172.16.0.131
    port => 9060
  }
}`

Tcpdump checks :

Received   1030 hep packets > 172.16.0.112.9060
Sent      76  hep packets > 172.16.0.131.9060
Sent    894  hep packets > 172.16.0.95.9060

Can you confirm if i'm going the good way and is even feasible ?

Thanks

**Comment by dvillaume** [comment]
I change my mind about the way to to it.
Thanks again for the project.

**Comment by lmangani** [comment]
Yes, it is possible, but certain limitations will depend on the node version in use.
