### ISSUE TITLE
paStash docker and Audiocodes optional filter

### ISSUE THREAD

**Issue by Wolffis** [sipcapture/paStash#82]
Hi,

I have tried to build up-to-date docker image for paStash and it launches ok with the given Dockerfile. However, if I want to add the Audiocodes SBC filter pastash_sonus.conf in the /config, I'll get the following:

[Thu, 28 Jan 2021 07:54:44 GMT] NOTICE Starting pastash 1.0.71
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Max http socket 100
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Loading config files from : /config
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Files loaded from directory, 3 urls found
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Loading config : 6 urls
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Initializing output HEP/EEP Server
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Start output to HEP udp to 127.0.0.1:9060
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Initializing filter AddHost
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Initializing filter AddTimestamp
[Thu, 28 Jan 2021 07:54:44 GMT] INFO Initializing filter AddVersion
Loading npm module... @pastash/filter_app_audiocodes
[Thu, 28 Jan 2021 07:54:44 GMT] ERROR Unable to load urls from command line
[Thu, 28 Jan 2021 07:54:44 GMT] ERROR TypeError: Cannot read property 'create' of undefined
    at LogstashAgent.configure (/usr/src/app/lib/agent.js:143:21)
    at LogstashAgent.<anonymous> (/usr/src/app/lib/agent.js:215:10)
    at /usr/src/app/node_modules/async/dist/async.js:3096:16
    at replenish (/usr/src/app/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/usr/src/app/node_modules/async/dist/async.js:983:17)
    at /usr/src/app/node_modules/async/dist/async.js:958:16
    at LogstashAgent.<anonymous> (/usr/src/app/lib/agent.js:265:5)
    at LogstashAgent.<anonymous> (/usr/src/app/lib/agent.js:220:7)
    at LogstashAgent.<anonymous> (/usr/src/app/lib/agent.js:156:9)
    at FilterAddVersion.<anonymous> (/usr/src/app/lib/lib/base_filter.js:36:5)

I have installed all sorts of dependencies into the image trying to solve the issue, but no luck so far. Is this something I can fix in the build process or some other error? Thanks!

**Comment by lmangani** [comment]
Hi @Wolffis - Please attach your Dockerfile to get assistance.

**Comment by Wolffis** [comment]
It's the default Dockerfile from Github

https://github.com/sipcapture/paStash/blob/next/Dockerfile

I have not really identified what could help in installing @pastash/filter_app_audiocodes other that of course

COPY pastash_sonus.conf /config/

I also tried to update the package.json with

npm install --unsafe-perm @pastash/filter_app_audiocodes

and it did add some dependencies, but it did not help in running the program. The problem might be related to zmq installation as there is even build_zmq.sh script added to the files...

**Comment by lmangani** [comment]
Oh its a lot easier than that if you build the container using the npm modules you want, ie:

### build
```
FROM node:12-alpine

RUN npm install --unsafe-perm -g @pastash/pastash @pastash/filter_app_audiocodes

EXPOSE 514
CMD [ "pastash", "--config_file=/pastash.conf" ]
```

### compose
```
pastash:
    image: your_pastash
    container_name: pastash
    volumes:
      - ./pastash.conf:/pastash.conf

 ```

**Comment by lmangani** [comment]
FYI some of the warnings for zmq etc are not breaking, the application works as long as you don't use those built in modules. As per above, the best way to build in a container is using the npm skimmed version. I hope this helps!
