### ISSUE TITLE
Installation fails on Debian 10

### ISSUE THREAD

**Issue by NiteCrwlr** [sipcapture/paStash#94]
Hi there!
I would like to test paStash with the Audiocodes Plugin, but I am not able to build it. There is some error with the zmq module and amqplib. Also installed libzmq3-dev, but did not help:

Here the command I used to install paStash:
```
npm install --unsafe-perm -g @pastash/pastash
```
Here is the error output:
```
make: *** [zmq.target.mk:103: Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/usr/lib/node_modules/@pastash/pastash/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.0-16-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/@pastash/pastash/node_modules/zmq
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for amqplib@0.5.1: wanted: {"node":">=0.8 <6 || ^6"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: amqplib@0.5.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 (node_modules/@pastash/pastash/node_modules/zmq):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Any help on this?

**Comment by lmangani** [comment]
This is normal. You need to have essential development tools installed to build (optional) dependencies of paStash.
The zmq-less paStash should be working anyhow - just confirm by launching it w/ the right recipe.

**Comment by lmangani** [comment]
Also I would NOT use node 10 or any OS provided node version! Current stable default is 14.x

**Comment by NiteCrwlr** [comment]
Hi  lmangani
Thank you for your fast response. I tried already with nodejs 14.x but it did not work. Then I downgraded to 10.x.
Now I will try with the right dependencies :)

**Comment by lmangani** [comment]
@NiteCrwlr pastash should be installed anyhow - those dependencies are optional and the audiocodes plugin doesn't need them. Could you confirm what happens when you just run `pastash` from your global path?

**Comment by NiteCrwlr** [comment]
Oh, seems like it's running:
pastash 
[Tue, 08 Jun 2021 09:27:22 GMT] NOTICE Starting pastash 1.0.72
[Tue, 08 Jun 2021 09:27:22 GMT] INFO Max http socket 100
[Tue, 08 Jun 2021 09:27:22 GMT] INFO Loading config : 3 urls
[Tue, 08 Jun 2021 09:27:22 GMT] INFO Initializing filter AddHost
[Tue, 08 Jun 2021 09:27:22 GMT] INFO Initializing filter AddTimestamp
[Tue, 08 Jun 2021 09:27:22 GMT] INFO Initializing filter AddVersion
[Tue, 08 Jun 2021 09:27:22 GMT] INFO Config loaded.

**Comment by lmangani** [comment]
told you so ;) those dependencies are optional, you can ignore any warning - let us know if you experience any issues with the plugin in a separate issue if needed

**Comment by NiteCrwlr** [comment]
Ok thanks! Sorry, I did not realize that it runs anyway :)

**Comment by lmangani** [comment]
No problem! It is confusing indeed :)

**Comment by 9-4-6** [comment]
> pastash

I have this problem too，
how did you solve it？

**Comment by 9-4-6** [comment]
> ou need to have essential development tools installed to build (optional) dependencies of paStash.
> The zmq-less paStash should be working anyhow - just confirm by launching it w/ the right recipe

I have this problem too，
how did you solve it？

**Comment by lmangani** [comment]
@CollectBugs welcome to pastash, please open a new issue and make sure you're using nodejs 14.x or 16.x
