### ISSUE TITLE
app_cisco (Cisco ISR) filter plugin DNS lookup error

### ISSUE THREAD

**Issue by runelucica** [sipcapture/paStash#99]
I am testing out the app_cisco filter for Cisco ISR devices.
I am running pastash as a container built using the following Dockerfile:

```
FROM node:17-alpine

RUN npm install --unsafe-perm -g @pastash/pastash @pastash/filter_app_audiocodes @pastash/filter_app_cisco

EXPOSE 514
CMD [ "pastash", "--config_file=/pastash.conf" ]
```

The pastash docker-compose service config is:

```
pastash:
    image: custom_pastash:17-alpine
    container_name: custom_pastash
    volumes:
      - ./pastash.conf:/pastash.conf
    ports:
      - "514:514/udp"
```

This is the pastash.config:

```
input {
  udp {
    host => 0.0.0.0
    port => 514
    type => syslog
  }
}
filter {
        if [udp_port] == 514  {
                multiline {
                  start_line_regex => /^<\d+?>\d+:\s(\*|)[A-Za-z]{3}\s{1,2}\d{1,2}\s\d{2}:\d{2}:\d{2}\.\d+.*ccsipDisplayMsg:/
                }
                app_cisco{
                  debug => true
                }
        }
}
output {
        hep {
          host => '1.2.3.4'
          port => 9060
          hep_id => 2223
          hep_type => 1
          hep_protocol => 6
        }
}
```

I am able to successfully send SIP messages as Syslog.

On pastash logs however I see these kind of errors:

```
Error: getaddrinfo ENOTFOUND sip-du-a-as.pstnhub.microsoft.com:5061
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'sip-du-a-as.pstnhub.microsoft.com:5061'
}
undefined
```

This particular Cisco ISR device is connecting to Microsoft Teams.
They send the identity of their SIP Proxies by using the port as well. 
It looks like pastash is trying to resolve the names with the ports included and this of course fails.

Is this working as designed or could I add something in the configuration to address this?

Many thanks for the help here.

**Comment by runelucica** [comment]
Could you please let me know if there is any additional information that I could provide to help further troubleshoot this issue?

Thanks.

**Comment by pierok13** [comment]
Let me check

**Comment by pierok13** [comment]
I pulled a request to delete that dns query as it was a try to do something that doesn't work. sorry for that.
[here](https://github.com/sipcapture/paStash/pull/100/commits/d42b614869966e97aba9edfe1ba25cc2a6710b9c)

**Comment by runelucica** [comment]
Many thanks.
Saw that dns variable at the beginning as well, but was not sure about what it did.
Happy to hear it is not really used.
Will build again once it is deleted and test.

**Comment by runelucica** [comment]
Hi.
Were the changes pushed? I am keen on testing again.

**Comment by lmangani** [comment]
Thanks @pierok13 new version published
```
+ @pastash/filter_app_cisco@1.0.2
```

**Comment by runelucica** [comment]
I just tested this again. And I am still getting a DNS issue, but this time a bit different:

```
Error: getaddrinfo ENOTFOUND .
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '.'
}
undefined
```


Were you able to successfully test it? Perhaps I am missing something.
I have the debug for the plugin filter set to debug (just like in the config pasted above).

**Comment by lmangani** [comment]
Thats not good. I have no data to test this but I think I can patch it up. Standby.

**Comment by lmangani** [comment]
@runelucica nothing too obvious in the code, it would appear as the srcIp was just a `.` (unlikely?)
are those errors constant or are there also successful extractions?
 It's really hard to tell without seeing the logs they stem from

**Comment by runelucica** [comment]
I have attached the SIP messages as a separate file.
The paStash debug log output is this one:

```
2021-11-10T12:41:55.603770780Z null
2021-11-10T12:41:55.603873544Z EXTERNAL_IP
2021-11-10T12:41:58.669639871Z null
2021-11-10T12:41:58.669680478Z EXTERNAL_IP
2021-11-10T12:41:59.672896218Z null
2021-11-10T12:41:59.672919305Z 0.0.0.9
```
Is that what we are supposed to see with logging set to debug?

These are the SIP messages:
[SIP Messages.txt](https://github.com/sipcapture/paStash/files/7512856/SIP.Messages.txt)

I replaced sensitive data with some text labels.

I don't see those error messages anymore in the pastash logs, but I don't see this in Homer either. Took a packet capture to see if anything is sent to the heplify-server on TCP 9060 (as configured), but I can't see anything.

Any other ideas would be appreciated.

**Comment by lmangani** [comment]
9060 is typically a UDP port, are you positive that's correct?

**Comment by runelucica** [comment]
I believe I am using TCP. I have several heplify agents running across the environment and all are configured to use TCP.
The ports exposed on the heplify-server docker-compose service are:
    ports:
      - "9060:9060"
      - "9096:9096"

And the heplify server configuration specifies only this address:
HEPTCPAddr            = "0.0.0.0:9060"

The other ones (HEPAddr and HEPTLSAddr) are commented out.

**Comment by runelucica** [comment]
Based on my latest testing the DNS error is not a problem anymore.
I have other ones for which I will open a separate issue.
Thanks for the help.
